mod "ntp",
    :git => "git://github.com/puppetlabs/puppetlabs-ntp.git"

mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
